name: Code scanning

on:
   push:
      paths-ignore:
         - '*.md'
         - '*.yml'
   pull_request:
      paths-ignore:
         - '*.md'
         - '*.yml'

jobs:
   code-scanning:
      name: detekt
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v2

         -  uses: actions/setup-java@v2
            with:
               distribution: 'zulu'
               java-version: '8'

         -  name: Detekt
            run: ./gradlew detekt

         -  uses: github/codeql-action/upload-sarif@v1
            if: ${{ !env.ACT }}
            with:
               sarif_file: build/reports/detekt/detekt.sarif
               checkout_path: ${{ github.workspace }}
