name: Scan with Detekt

on:
   push:
      paths-ignore:
         - '*.md'
         - '*.yml'
   pull_request:
      paths-ignore:
         - '*.md'
         - '*.yml'
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

jobs:
   code-scanning:
      name: detekt
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v3

         -  uses: actions/setup-java@v3
            with:
               distribution: 'zulu'
               java-version: '8'

         -  name: Detekt
            continue-on-error: true
            uses: gradle/gradle-build-action@v2
            with:
               arguments: detekt

         -  uses: github/codeql-action/upload-sarif@v1
            if: ${{ !env.ACT }}
            continue-on-error: true
            with:
               sarif_file: build/reports/detekt/detekt.sarif
               checkout_path: ${{ github.workspace }}
