name: master

on:
   push:
      paths-ignore:
         - '*.md'
         - '*.yml'
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: Setup JDK
            uses: actions/setup-java@v1
            with:
               java-version: '11'

         -  name: Run tests
            run: ./gradlew check

         -  name: publish snapshots
            run: ./gradlew publish
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
               ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
               ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip


env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
