name: PR-Test

on:
   pull_request:
      paths-ignore:
         - '*.md'
         - '*.yml'

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v3

         -  name: Setup JDK
            uses: actions/setup-java@v3
            with:
               distribution: 'zulu'
               java-version: '8'

         -  name: Run tests
            uses: gradle/gradle-build-action@v2
            with:
               arguments: check

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
